### ISSUE TITLE
Promise is pending and the variables are undefined. (bakana.TenxMatrixMarketDataset)

### ISSUE THREAD

**Issue by ygao61** [kanaverse/bakana#73]
Hi,

I am trying to use the 'bakana' in my node.js script to load 10x matrix data and run the analysis, but I have some trouble in loading the data. For example, I pass the mtx and feature file to the bakana, but I cannot get the output of .summary(), the state of the promise is pending and the variable is undefined.

Besides, I also failed to follow the tutorial about "bakana.runAnalysis" in the readme file , even with the test files.
(I am not sure if "async" would be the point? I tried several ways to deal with the async problem, I still get "undefined" result.)

I would be really appreciate that if there are any suggestions or solutions. Thank you so much!

Best,
Yuan

**Comment by jkanche** [comment]
perhaps one of the tests that loads a 10x dataset would be a good start - https://github.com/kanaverse/bakana/blob/master/tests/10X.test.js

if the issue persists, can you share a snippet of what you are trying to do?

**Comment by jkanche** [comment]
just realized, depending on the version of node you have installed, you might need to enable the flags mentioned here - https://github.com/kanaverse/scran.js/issues/70

**Comment by ygao61** [comment]
> just realized, depending on the version of node you have installed, you might need to enable the flags mentioned here - [kanaverse/scran.js#70](https://github.com/kanaverse/scran.js/issues/70)

Yep, it works now!!Thank you.
